name: Spellcheck Action

on:
  push:

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rojopolis/spellcheck-github-actions@v0
        run: aspell --mode=markdown --lang=en --personal=.aspell.en.pws list < strengths_and_weaknesses.md
